{% extends "layout.phtml" %}


{% block content %}

<div class="b-form_shortener js-form_shortener">

    <div class="b-form_shortener_cnt clearfix">
        <div class="b-form_shortener__item">
            <input class="b-form__input js-url_original" type="text" value="" placeholder="вставте ссылку" name="url_original"/>
        </div>
        <div class="b-form_shortener__item">
            <button class="b-form__button js-short" disabled>Укоротить</button>
        </div>
    </div>

    <div class="b-result on-url_shortened">

    </div>
</div>
{% endblock %}