<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/css/main.css">


</head>
<body>
{% block content %}{% endblock %}

<script type="text/javascript" src="/js/lib/jquery/jquery-1.12.0.min.js"></script>
<script type="text/javascript" src="/js/lib/underscore/underscore-min.js"></script>
<script type="text/javascript" src="/js/lib/backbone/backbone-min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
</body>
</html>